# list DraCor URLs for plays of Gogol 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dracon: <http://dracor.org/ontology#>
SELECT ?play
WHERE {
  ?author owl:sameAs <http://www.wikidata.org/entity/Q43718> .
  ?play dracon:has_author ?author
}
LIMIT 50
