# Compose file for test setup
# Usage: docker compose -f compose.yml -f compose.t.yml up
# This file is named compose.t.yml instead of compose.test.yml to work around
# the VS Code quirk of association the wrong schema with the latter name.
name: dracor-test
services:
  api:
    image: dracor/api-test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FUSEKI_SECRET=qwerty
        - GITHUB_WEBHOOK_SECRET=qwerty
    environment:
      - DRACOR_API_BASE=http://localhost:8081/exist/restxq/v1
      - EXIST_PASSWORD=
    ports:
      - 8081:8080
  frontend:
    profiles:
      - fulltest
    ports:
      - 8089:80
