services:
  api:
    image: "dracor/dracor-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TRIPLESTORE_SERVER=blazegraph:8889
        - METRICS_SERVER=metrics:8030
    ports:
      - "8080:8080"
    volumes:
      - .:/tmp/export
    depends_on:
      - blazegraph
      - metrics
    links:
      - metrics
      - blazegraph
  blazegraph:
    image: "lyrasis/blazegraph:2.1.5"
    ports:
      - "8889:8080"
    expose:
      - "8889"
  metrics:
    build: https://github.com/dracor-org/dracor-metrics.git#main
    ports:
      - "8030:8030"
