# FIXME: This is going to be osolete and should be remove when we introduce the
# schemathesis tests.
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COMPOSE_FILE: compose.yml
  DOCKER_BUILDKIT: 1
  FORCE_COLOR: 1

jobs:
  compose-up:
    name: Test docker compose up can start services
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker --version
      - name: Start the docker-compose stack
        run: docker compose up --detach --wait
      - name: Test if /info returns a response
        run: curl --verbose http://localhost:8088/api/v1/info
      - name: Stop the docker-compose stack
        run: docker compose down
        if: always()
